baseURL = 'https://ortalks.online/'
author = "运筹OR帷幄"
copyright = "运筹OR帷幄"
paginate = 10
DefaultContentLanguage = "zh-CN"
theme = 'tailwind'


[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "landing"

  [params.header]
    title = "test"
    logo = "favicon.ico"

  [params.footer]
    since = 2018
    poweredby = false

[menu]

  [[menu.main]]
    identifier = "ortalks"
    name = "OR Talk"
    pageRef = "/ortalk"
    weight = 10

   [[menu.main]]
    identifier = "techtalks"
    name = "Tech Talk"
    pageRef = "/techtalk"
    weight = 20

    [[menu.main]]
    identifier = "intalks"
    name = "In Talk"
    pageRef = "/intalk"
    weight = 30

[taxonomies]
category = "categories"
tag = "tags"

[Languages]
[Languages.zh-CN]
title = "运筹OR帷幄直播汇总"
weight = 0
languagename = "中文"

[Languages.en]
title = "ORAI China"
weight = 1
languagename = "English"